"""initial schema

Revision ID: c038ccbada72
Revises: 
Create Date: 2026-08-16 10:23:48.178663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c038ccbada72'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('institution', sa.String(length=64), nullable=False),
    sa.Column('last_verified_balance_paise', sa.Integer(), nullable=True),
    sa.Column('last_reconciled_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('entity', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('before', sa.Text(), nullable=False),
    sa.Column('after', sa.Text(), nullable=False),
    sa.Column('reason', sa.String(length=128), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_payload', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pending_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('step', sa.String(length=32), nullable=False),
    sa.Column('context_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('vpas', sa.String(length=256), nullable=False),
    sa.Column('aliases', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recurring',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pattern', sa.String(length=16), nullable=False),
    sa.Column('expected_amount', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('merchant', sa.String(length=128), nullable=False),
    sa.Column('day_of_month', sa.Integer(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('txn_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('posting_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('amount_paise', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('fx_rate', sa.Float(), nullable=True),
    sa.Column('type', sa.String(length=8), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('counterparty_norm', sa.String(length=128), nullable=False),
    sa.Column('account', sa.String(length=32), nullable=False),
    sa.Column('utr', sa.String(length=64), nullable=True),
    sa.Column('key_exact', sa.String(length=64), nullable=True),
    sa.Column('key_soft', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('lifecycle', sa.String(length=16), nullable=False),
    sa.Column('txn_state', sa.String(length=24), nullable=False),
    sa.Column('credit_type', sa.String(length=16), nullable=True),
    sa.Column('ownership', sa.String(length=8), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('bill_id', sa.String(length=32), nullable=True),
    sa.Column('emi_group', sa.String(length=32), nullable=True),
    sa.Column('sources', sa.String(length=128), nullable=False),
    sa.Column('parser_version', sa.Integer(), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_txn_counterparty_date', 'transactions', ['counterparty_norm', 'txn_date'], unique=False)
    op.create_index('ix_txn_key_exact', 'transactions', ['key_exact'], unique=True)
    op.create_table('dedup_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('raw_id', sa.String(length=128), nullable=False),
    sa.Column('matched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['canonical_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('person', sa.String(length=64), nullable=False),
    sa.Column('full_amount', sa.Integer(), nullable=False),
    sa.Column('share_amount', sa.Integer(), nullable=True),
    sa.Column('expected_receivable', sa.Integer(), nullable=False),
    sa.Column('received_so_far', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refund_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('txn_id', sa.Integer(), nullable=False),
    sa.Column('original_txn_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('matched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['original_txn_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['txn_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settlements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('txn_id', sa.Integer(), nullable=False),
    sa.Column('group_expense_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_expense_id'], ['group_expenses.id'], ),
    sa.ForeignKeyConstraint(['txn_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settlements')
    op.drop_table('refund_links')
    op.drop_table('group_expenses')
    op.drop_table('dedup_map')
    op.drop_index('ix_txn_key_exact', table_name='transactions')
    op.drop_index('ix_txn_counterparty_date', table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('recurring')
    op.drop_table('persons')
    op.drop_table('pending_actions')
    op.drop_table('events')
    op.drop_table('audit')
    op.drop_table('accounts')
    # ### end Alembic commands ###
